# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Old9WMrRdIbRQdzZ3hY-f6LMW6tk-wE
"""

import pandas as pd
from datetime import datetime

attendance_data = [
    {"student_id": 101, "date": "2024-03-01", "status": "Absent"},
    {"student_id": 101, "date": "2024-03-02", "status": "Absent"},
    {"student_id": 101, "date": "2024-03-03", "status": "Absent"},
    {"student_id": 101, "date": "2024-03-04", "status": "Absent"},
    {"student_id": 101, "date": "2024-03-05", "status": "Present"},
    {"student_id": 102, "date": "2024-03-02", "status": "Absent"},
    {"student_id": 102, "date": "2024-03-03", "status": "Absent"},
    {"student_id": 102, "date": "2024-03-04", "status": "Absent"},
    {"student_id": 102, "date": "2024-03-05", "status": "Absent"},
    {"student_id": 103, "date": "2024-03-05", "status": "Absent"},
    {"student_id": 103, "date": "2024-03-06", "status": "Absent"},
    {"student_id": 103, "date": "2024-03-07", "status": "Absent"},
    {"student_id": 103, "date": "2024-03-08", "status": "Absent"},
    {"student_id": 103, "date": "2024-03-09", "status": "Absent"},
    {"student_id": 104, "date": "2024-03-01", "status": "Present"},
    {"student_id": 104, "date": "2024-03-02", "status": "Present"},
    {"student_id": 104, "date": "2024-03-03", "status": "Absent"},
    {"student_id": 104, "date": "2024-03-04", "status": "Present"},
    {"student_id": 104, "date": "2024-03-05", "status": "Present"}
]

df = pd.DataFrame(attendance_data)
df["date"] = pd.to_datetime(df["date"])
df.sort_values(by=["student_id", "date"], inplace=True)

absence_summary = {}
absence_streak = []
previous_student = None

for _, record in df.iterrows():
    student = record["student_id"]
    current_date = record["date"]
    attendance_status = record["status"]

    if student != previous_student:
        if previous_student is not None and len(absence_streak) >= 3:
            absence_summary[previous_student] = {
                "student_id": previous_student,
                "start_date": absence_streak[0],
                "end_date": absence_streak[-1],
                "total_days": len(absence_streak),
            }
        absence_streak = []

    if attendance_status == "Absent":
        absence_streak.append(current_date.strftime("%Y-%m-%d"))
    else:
        if len(absence_streak) >= 3:
            absence_summary[student] = {
                "student_id": student,
                "start_date": absence_streak[0],
                "end_date": absence_streak[-1],
                "total_days": len(absence_streak),
            }
        absence_streak = []

    previous_student = student

if len(absence_streak) >= 3:
    absence_summary[previous_student] = {
        "student_id": previous_student,
        "start_date": absence_streak[0],
        "end_date": absence_streak[-1],
        "total_days": len(absence_streak),
    }

result_df = pd.DataFrame(absence_summary.values())
result_df = result_df[["student_id", "start_date", "end_date", "total_days"]]

print(result_df)